### ISSUE TITLE
Toggles do not highlight atoms in SMILES string.

### ISSUE THREAD

**Issue by vfscalfani** [ualibweb/SmiNav#1]
@AveryUALibrary 

When the "Highlight Neighbors" or "Show Containing Rings" boxes are checked, it does not highlight the additional atoms in the corresponding SMILES string. I thought we had this working before? If not, then it's a feature request. This would make everything mapped together.

Thanks, 

Vin

**Comment by ghost** [comment]
Fixed in the new release
