### ISSUE TITLE
Feature Request: Add atom index

### ISSUE THREAD

**Issue by vfscalfani** [ualibweb/SmiNav#2]
@AveryUALibrary for next release, it would be great to add the atom index numbers under the SMILES string and next to atoms in depiction. We can put all of the indices or maybe the indices appear as you click on a SMILES atom or atom in depiction. thanks!

https://www.rdkit.org/docs/Cookbook.html#include-an-atom-index

**Comment by ghost** [comment]
Atom Indices should now show up in both the smiles string and underneath each atom in the visualization
